// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file contains the Genkit flow for enhancing listing descriptions using AI.
 *
 * - enhanceListingDescription - A function that takes an item description as input and returns suggestions for improvement.
 * - EnhanceListingDescriptionInput - The input type for the enhanceListingDescription function.
 * - EnhanceListingDescriptionOutput - The return type for the enhanceListingDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const EnhanceListingDescriptionInputSchema = z.object({
  description: z.string().describe('The item description to be enhanced.'),
  title: z.string().describe('The title of the item being listed.'),
  category: z.string().describe('The category of the item being listed.'),
});

export type EnhanceListingDescriptionInput = z.infer<
  typeof EnhanceListingDescriptionInputSchema
>;

const EnhanceListingDescriptionOutputSchema = z.object({
  enhancedDescription: z
    .string()
    .describe('The enhanced item description.'),
  suggestedTags: z
    .array(z.string())
    .describe('Suggested tags for the item listing.'),
});

export type EnhanceListingDescriptionOutput = z.infer<
  typeof EnhanceListingDescriptionOutputSchema
>;

export async function enhanceListingDescription(
  input: EnhanceListingDescriptionInput
): Promise<EnhanceListingDescriptionOutput> {
  return enhanceListingDescriptionFlow(input);
}

const enhanceListingDescriptionPrompt = ai.definePrompt({
  name: 'enhanceListingDescriptionPrompt',
  input: {schema: EnhanceListingDescriptionInputSchema},
  output: {schema: EnhanceListingDescriptionOutputSchema},
  prompt: `You are an AI assistant helping users improve their item descriptions for an online marketplace.

  Given the item's current description, title, and category, suggest improvements to make it more appealing and visible to potential buyers.
  Also, suggest relevant tags to increase its searchability.

  Item Title: {{{title}}}
  Item Category: {{{category}}}
  Current Description: {{{description}}}

  Please provide an enhanced description and a list of suggested tags.
  Enhanced Description:
  Suggested Tags:`, // Ensure the output is valid JSON.
});

const enhanceListingDescriptionFlow = ai.defineFlow(
  {
    name: 'enhanceListingDescriptionFlow',
    inputSchema: EnhanceListingDescriptionInputSchema,
    outputSchema: EnhanceListingDescriptionOutputSchema,
  },
  async input => {
    const {output} = await enhanceListingDescriptionPrompt(input);
    return output!;
  }
);
